const mongoose = require('mongoose');
const path = require('path');
const dotenv = require('dotenv');
const Property = require('../models/Property');
const Review = require('../models/Review');
const Roommate = require('../models/Roommate');

dotenv.config({ path: path.resolve(__dirname, '../../atlas-credentials.env') });
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const sampleProperties = [
  {
    title: 'Luxury South-Facing 3BHK Apartment with Lake View in Gulshan-2',
    description: 'Ultra-modern 3-bedroom, 4-bathroom apartment located in the diplomatic zone of Gulshan-2. Features imported marble flooring, modular kitchen with official Titas line gas, centralized water heating, floor-to-ceiling soundproof double-glazed windows, and full 24/7 generator backup for AC & all appliances.',
    propertyType: 'Family Apartment',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Gulshan 2',
    address: 'Road 55, House 12, Gulshan-2, Dhaka 1212',
    rent: 120000,
    serviceCharge: 12000,
    advanceDepositMonths: 3,
    negotiable: false,
    bedrooms: 3,
    bathrooms: 4,
    balconies: 3,
    sizeSqFt: 2450,
    floor: '6th of 10 floors',
    facing: 'South',
    gasType: 'Titas Line Gas',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.7925, lng: 90.4152 },
    metroNearby: 'Gulshan Circle-2 / Diplomatic Zone',
    landmarks: ['Gulshan Lake Park (200m)', 'Westin Hotel (3 min)', 'Unimart Gulshan'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: true,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Family Only',
    availableFrom: '1st October 2026',
    contactName: 'Engr. M. A. Karim',
    contactPhone: '+8801711223344',
    contactWhatsApp: '+8801711223344',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.9,
    reviewCount: 14,
    status: 'Available',
  },
  {
    title: 'Spacious 3 Bed Flat Near Dhanmondi Lake & Mastermind School',
    description: 'Well-ventilated, sunlit 3 BHK flat situated on Dhanmondi Road 8A. Walking distance to Dhanmondi Lake, leading schools, and supermarkets. Titas gas connection available, separate dining and drawing hall, modern fittings, and private dedicated car parking space.',
    propertyType: 'Family Apartment',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Dhanmondi',
    address: 'Road 8A, House 24, Dhanmondi R/A, Dhaka 1209',
    rent: 48000,
    serviceCharge: 6000,
    advanceDepositMonths: 2,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    sizeSqFt: 1850,
    floor: '4th of 7 floors',
    facing: 'South',
    gasType: 'Titas Line Gas',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.7461, lng: 90.3742 },
    metroNearby: 'Science Lab / Karwan Bazar Metro Station',
    landmarks: ['Dhanmondi Lake Walkway (100m)', 'Mastermind School', 'Shwapno Super Shop'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: true,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Family Only',
    availableFrom: 'Immediate',
    contactName: 'Mrs. Selina Akhter',
    contactPhone: '+8801819334455',
    contactWhatsApp: '+8801819334455',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.8,
    reviewCount: 9,
    status: 'Available',
  },
  {
    title: 'Bachelor / Student Friendly 3 Bed Flat in Bashundhara Block-D',
    description: 'Ideal for university students (NSU, IUB, AIUB) or working professionals. Spacious 3 bedrooms with attached bathrooms, large balcony, high-speed fiber internet wiring, and quiet study-friendly environment. Landlord has zero hassle policy for bachelors.',
    propertyType: 'Family Apartment',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Bashundhara R/A',
    address: 'Road 7, Block D, Bashundhara Residential Area, Dhaka',
    rent: 28000,
    serviceCharge: 4000,
    advanceDepositMonths: 2,
    negotiable: false,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    sizeSqFt: 1450,
    floor: '5th of 6 floors',
    facing: 'East',
    gasType: 'Cylinder (LPG)',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.8164, lng: 90.4357 },
    metroNearby: 'Kuril Flyover / Metro feeder',
    landmarks: ['North South University (NSU 5 min)', 'IUB Campus', 'Evercare Hospital (1km)'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: false,
      rooftopAccess: true,
      servantRoom: false,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Bachelor & Family',
    availableFrom: '1st November 2026',
    contactName: 'Tanvir Hossain',
    contactPhone: '+8801912445566',
    contactWhatsApp: '+8801912445566',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.7,
    reviewCount: 19,
    status: 'Available',
  },
  {
    title: 'Modern 3 Bed Flat with Titas Gas in Uttara Sector 11 (Near Metro)',
    description: 'Brand new luxury building in Uttara Sector 11. 4-minute walk to Uttara Center Metro Rail Station. Equipped with dual elevator system, standby silent generator, CCTV surveillance, 24-hr security, and intercom.',
    propertyType: 'Family Apartment',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Uttara',
    address: 'Road 18, Sector 11, Uttara Model Town, Dhaka 1230',
    rent: 36000,
    serviceCharge: 4500,
    advanceDepositMonths: 2,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    sizeSqFt: 1600,
    floor: '3rd of 8 floors',
    facing: 'South',
    gasType: 'Titas Line Gas',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.8759, lng: 90.3795 },
    metroNearby: 'Uttara Center Metro Station (4 min walk)',
    landmarks: ['Sector 11 Park', 'Zamzam Tower', 'Rajuk Uttara Model College'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: true,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Family Only',
    availableFrom: 'Immediate',
    contactName: 'Dr. Anwarul Huq',
    contactPhone: '+8801730998877',
    contactWhatsApp: '+8801730998877',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.9,
    reviewCount: 11,
    status: 'Available',
  },
  {
    title: 'Secured 3 BHK Apartment in Mirpur DOHS with Garden View',
    description: 'Peaceful and highly secured living inside Mirpur Defence Officers Housing Society (DOHS). Open field in front, wide jogging tracks, community mosque, community center, and strict entry checkpoints for superior safety.',
    propertyType: 'Family Apartment',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Mirpur DOHS',
    address: 'Avenue 4, Road 9, Mirpur DOHS, Dhaka 1216',
    rent: 42000,
    serviceCharge: 5500,
    advanceDepositMonths: 2,
    negotiable: false,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    sizeSqFt: 1780,
    floor: '5th of 7 floors',
    facing: 'South-East',
    gasType: 'Titas Line Gas',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.8344, lng: 90.3662 },
    metroNearby: 'Pallabi Metro Station (5 min)',
    landmarks: ['Mirpur DOHS Central Park', 'DOHS Mosque', 'MIST & BUP nearby'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: true,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Family Only',
    availableFrom: '1st October 2026',
    contactName: 'Major (Retd.) S. Rahman',
    contactPhone: '+8801715556677',
    contactWhatsApp: '+8801715556677',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 5.0,
    reviewCount: 7,
    status: 'Available',
  },
  {
    title: 'Female Bachelor Master Bedroom Sublet in Bashundhara Block-C',
    description: 'Fully furnished single master bedroom for female student or working woman in a modern flat. Includes attached bathroom with geyser, private attached south-facing balcony, high speed WiFi, refrigerator share, and maid service included in rent.',
    propertyType: 'Bachelor Sublet',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Bashundhara R/A',
    address: 'Road 3, Block C, Bashundhara R/A, Dhaka',
    rent: 11000,
    serviceCharge: 1500,
    advanceDepositMonths: 1,
    negotiable: false,
    bedrooms: 1,
    bathrooms: 1,
    balconies: 1,
    sizeSqFt: 280,
    floor: '2nd of 6 floors',
    facing: 'South',
    gasType: 'Cylinder (LPG)',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.8131, lng: 90.4312 },
    metroNearby: 'Kuril Flyover',
    landmarks: ['Near Apollo / Evercare Hospital', 'NSU Walkway'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: false,
      rooftopAccess: true,
      servantRoom: false,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Bachelor (Female)',
    availableFrom: 'Immediate',
    contactName: 'Faria Tasnim',
    contactPhone: '+8801680112233',
    contactWhatsApp: '+8801680112233',
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.9,
    reviewCount: 16,
    status: 'Available',
  },
  {
    title: 'Executive Penthouse Duplex with Rooftop Garden in Banani',
    description: 'Spectacular 4BHK duplex penthouse in Banani Block-F. Features 3,400 sq.ft of luxurious living space, private landscaped roof terrace with BBQ corner, double-height ceiling living hall, smart home automation, and 2 dedicated basement car parkings.',
    propertyType: 'Duplex House',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Banani',
    address: 'Road 11, Block F, Banani, Dhaka 1213',
    rent: 175000,
    serviceCharge: 15000,
    advanceDepositMonths: 3,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 4,
    sizeSqFt: 3400,
    floor: '8th & 9th Duplex',
    facing: 'South-West',
    gasType: 'Titas Line Gas',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.7937, lng: 90.4048 },
    metroNearby: 'Banani Bridge / Kemal Ataturk Avenue',
    landmarks: ['Banani 11 Dining Hub', 'Presidency University', 'Sheraton Dhaka'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: true,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Any',
    availableFrom: '1st October 2026',
    contactName: 'Kamal Uddin Ahmed',
    contactPhone: '+8801712990011',
    contactWhatsApp: '+8801712990011',
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 5.0,
    reviewCount: 6,
    status: 'Available',
  },
  {
    title: 'Budget Family 2 Bed Flat in Mohammadpur Japan Garden City Area',
    description: 'Comfortable 2 bedroom apartment near Ring Road, Mohammadpur. Safe gated environment, 24/7 security, nearby grocery markets, schools, and quick transport links to Dhanmondi and Farmgate. Line gas connection active.',
    propertyType: 'Family Apartment',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Mohammadpur',
    address: 'Ring Road, Adabor, Mohammadpur, Dhaka 1207',
    rent: 22000,
    serviceCharge: 3000,
    advanceDepositMonths: 2,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 2,
    sizeSqFt: 1050,
    floor: '4th of 6 floors',
    facing: 'North',
    gasType: 'Titas Line Gas',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.7667, lng: 90.3582 },
    metroNearby: 'Agargaon Metro Station (10 min)',
    landmarks: ['Japan Garden City Complex', 'Suchona Community Center', 'St. Joseph Higher Secondary'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: false,
      rooftopAccess: true,
      servantRoom: false,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Family Only',
    availableFrom: 'Immediate',
    contactName: 'Nasir Chowdhury',
    contactPhone: '+8801911778899',
    contactWhatsApp: '+8801911778899',
    images: [
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: false,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.6,
    reviewCount: 12,
    status: 'Available',
  },
  {
    title: 'Prime 3 BHK Residential Flat in Nasirabad Housing Society, Chittagong',
    description: 'Premium family home in the elite Nasirabad Housing Society, Chittagong. Serene green hill view, fresh air, 3 spacious bedrooms, wide balconies, covered parking, and 24-hr generator backup.',
    propertyType: 'Family Apartment',
    division: 'Chittagong',
    city: 'Chittagong',
    area: 'Nasirabad Housing Society',
    address: 'Road 3, Nasirabad H/S, Chittagong 4000',
    rent: 38000,
    serviceCharge: 4500,
    advanceDepositMonths: 2,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    sizeSqFt: 1750,
    floor: '3rd of 6 floors',
    facing: 'South',
    gasType: 'Cylinder (LPG)',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 22.3667, lng: 91.8222 },
    metroNearby: 'GEC Circle Chittagong',
    landmarks: ['Chittagong Club (5 min)', 'Khulshi Mart', 'Sanmar Ocean City'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: true,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Family Only',
    availableFrom: '1st October 2026',
    contactName: 'Syed Nurul Islam',
    contactPhone: '+8801819887766',
    contactWhatsApp: '+8801819887766',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.9,
    reviewCount: 8,
    status: 'Available',
  },
  {
    title: 'Fully Furnished Studio Apartment in Gulshan-1',
    description: 'Chic, plug-and-play modern studio apartment in Gulshan-1. Equipped with smart TV, inverter AC, king-size bed, workstation, microwave, induction cooker, washing machine, and 200 Mbps fiber WiFi. Perfect for corporate expats and consultants.',
    propertyType: 'Studio Flat',
    division: 'Dhaka',
    city: 'Dhaka',
    area: 'Gulshan 1',
    address: 'Road 134, Gulshan-1, Dhaka 1212',
    rent: 45000,
    serviceCharge: 5000,
    advanceDepositMonths: 2,
    negotiable: false,
    bedrooms: 1,
    bathrooms: 1,
    balconies: 1,
    sizeSqFt: 620,
    floor: '7th of 12 floors',
    facing: 'East',
    gasType: 'Induction/Electric',
    electricityType: 'Prepaid Meter',
    coordinates: { lat: 23.7788, lng: 90.4184 },
    metroNearby: 'Gulshan-1 Circle',
    landmarks: ['Police Plaza Concord', 'Hatirjheel Walkway (2 min)', 'Gulshan DCC Market'],
    amenities: {
      generatorBackup: true,
      lift: true,
      guard247: true,
      cctv: true,
      carParking: true,
      rooftopAccess: true,
      servantRoom: false,
      wifiAvailable: true,
      geyser: true,
    },
    tenantPolicy: 'Any',
    availableFrom: 'Immediate',
    contactName: 'Rezaul Karim Real Estate',
    contactPhone: '+8801700112244',
    contactWhatsApp: '+8801700112244',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    verified: true,
    nidVerified: true,
    deedVerified: true,
    rating: 4.8,
    reviewCount: 22,
    status: 'Available',
  },
];

const sampleRoommates = [
  {
    title: 'Roommate Needed for Master Bed with Attached Bath in Bashundhara D-Block',
    posterName: 'Saadman Sakib',
    posterGender: 'Male',
    userType: 'University Student',
    institutionOrCompany: 'North South University (CSE Department)',
    area: 'Bashundhara R/A',
    city: 'Dhaka',
    budgetBDT: 9500,
    roomType: 'Single Attached Bath',
    availableFrom: '1st October',
    habits: {
      smoking: false,
      studyFriendly: true,
      cookingShared: true,
      nightOwl: true,
    },
    contactPhone: '+8801799887766',
    contactWhatsApp: '+8801799887766',
    description: 'Looking for a calm, non-smoking NSU/IUB student or job holder. The room has attached bath, geyser, fast WiFi, and full maid service included.',
  },
  {
    title: 'Female Flatmate Required for Single Bedroom in Dhanmondi 9A',
    posterName: 'Nusrat Jahan',
    posterGender: 'Female',
    userType: 'Job Holder / Professional',
    institutionOrCompany: 'Software Engineer @ bKash',
    area: 'Dhanmondi',
    city: 'Dhaka',
    budgetBDT: 12000,
    roomType: 'Single Master Bed',
    availableFrom: 'Immediate',
    habits: {
      smoking: false,
      studyFriendly: true,
      cookingShared: true,
      nightOwl: false,
    },
    contactPhone: '+8801822334455',
    contactWhatsApp: '+8801822334455',
    description: 'Safe gated apartment for female professional or student. Line gas active, lift, 24/7 security guard.',
  },
  {
    title: '1 Seat Available in 2-Person Shared Room in Mirpur-10',
    posterName: 'Rashedul Hasan',
    posterGender: 'Male',
    userType: 'University Student',
    institutionOrCompany: 'DU Student / Job Aspirant',
    area: 'Mirpur-10',
    city: 'Dhaka',
    budgetBDT: 4500,
    roomType: 'Shared Room Seat',
    availableFrom: '1st November',
    habits: {
      smoking: false,
      studyFriendly: true,
      cookingShared: true,
      nightOwl: false,
    },
    contactPhone: '+8801933445566',
    contactWhatsApp: '+8801933445566',
    description: 'Near Mirpur-10 Metro Rail Station. Easy commute to Dhaka University and Motijheel.',
  },
];

async function seedDB() {
  try {
    let uri = process.env.MONGODB_URI;
    if (!uri.includes('griho_db')) {
      if (uri.includes('?')) {
        uri = uri.replace('?', 'griho_db?');
      } else {
        uri = uri.endsWith('/') ? `${uri}griho_db` : `${uri}/griho_db`;
      }
    }

    await mongoose.connect(uri, { serverSelectionTimeoutMS: 10000 });
    console.log('[Seed] Connected to MongoDB Atlas');

    await Property.deleteMany({});
    await Review.deleteMany({});
    await Roommate.deleteMany({});
    console.log('[Seed] Cleared existing properties, reviews, and roommate posts');

    const createdProps = await Property.insertMany(sampleProperties);
    console.log(`[Seed] Seeded ${createdProps.length} properties.`);

    // Seed sample reviews for the first 3 properties
    const reviewsToSeed = [
      {
        property: createdProps[0]._id,
        authorName: 'Tahmidur Rahman',
        authorRole: 'Verified Resident',
        rating: 5,
        safetyRating: 5,
        gasWaterRating: 5,
        comment: 'Amazing peaceful building in Gulshan-2. Titas line gas pressure is always top notch and the 24/7 standby generator never leaves you without electricity.',
      },
      {
        property: createdProps[0]._id,
        authorName: 'Farhana Yasmin',
        authorRole: 'Tenant',
        rating: 5,
        safetyRating: 5,
        gasWaterRating: 5,
        comment: 'Very cooperative landlord. Security guards are polite and CCTV keeps the premises secure.',
      },
      {
        property: createdProps[1]._id,
        authorName: 'Ashfaq Ahmed',
        authorRole: 'Tenant',
        rating: 5,
        safetyRating: 5,
        gasWaterRating: 4,
        comment: 'Living near Dhanmondi lake walkway is a blessing for morning walks. Very airy flat with great sunlight.',
      },
      {
        property: createdProps[2]._id,
        authorName: 'Mahir Faysal',
        authorRole: 'Tenant',
        rating: 5,
        safetyRating: 4,
        gasWaterRating: 5,
        comment: 'Best bachelor-friendly building in Bashundhara D-Block. Landlord is extremely friendly and understanding with students.',
      },
    ];

    await Review.insertMany(reviewsToSeed);
    console.log('[Seed] Seeded verified tenant reviews.');

    await Roommate.insertMany(sampleRoommates);
    console.log(`[Seed] Seeded ${sampleRoommates.length} roommate / sublet listings.`);

    await mongoose.connection.close();
    console.log('[Seed Completed Successfully!]');
    process.exit(0);
  } catch (error) {
    console.error('[Seed Error]:', error);
    process.exit(1);
  }
}

seedDB();
